User_name = input("What is your name? ")
Age = input("What is your age? ")
print("hi {User_name} You are {Age} years old.")
color = input("What is your favorite color? ")
food = input("What is your favorite food? ")
hobby = input("What is your favorite hobby? ")
print("You love {color}, enjoy eating {food}, and like to {hobby}.")
word = input("Enter a word: ")
print("First letter: {word[0]}")
print("Last letter: {word[-1]}")
print("Uppercase: {word.upper()}")
print("Reversed: {word[::-1]}")
