User_name = input("What is your name? ")
Age = input("What is your age? ")
print(f"hi {User_name} You are {Age} years old.")
color = input("What is your favorite color? ")
food = input("What is your favorite food? ")
hobby = input("What is your favorite hobby? ")
print(f"You love {color}, enjoy eating {food}, and like to {hobby}.")
word = input("Enter a word: ")
print(f"First letter: {word[0]}")
print(f"Last letter: {word[-1]}")
print("Uppercase: {word.upper()}")
print(f"Reversed: {word[::-1]}")
