name=input("What is your name")
color=input("What is your favorite color?")
movie=input("What is your favorite movie?")
food=input("What is your favorite food?")
subject=input("What is your favorite subject?")
print("Your name is", name)
print("Your favorite color is", color)
print("Your favorite movie is", movie)
print("Your favorite food is", food)
print("Your favorite subject is", subject)